[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
anchor_nft_proj = "BqWZM1vE46HuM5yTD9oMaMitjG1572QYwoNZFxW3yTgE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rootster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
